### ISSUE TITLE
对于字符串的疑问

### ISSUE THREAD

**Issue by myb007** [cfsmile/ooppy#11]
a=‘python’
此时a也可以用a[i]来修改里面的值是为什么

**Comment by wtyuyuyu** [comment]
‘python’是字符串额，字符串的值不能更改，你是怎么做到的
我照你说的用a[i]修改，报错了
TypeError: 'str' object does not support item assignment

**Comment by myb007** [comment]
我后来也改了，也报错了不过之前没报过错啊=-=

**Comment by cfsmile** [comment]
@myb007 需要提供原始实验记录，才好重复实验，复现实验中的错误。以后，留意保留实验记录吧。

**Comment by myb007** [comment]
好的，我知道了

**Comment by myb007** [comment]
好的，我知道了

**Comment by passengeryjy** [comment]
报错了

**Comment by cfsmile** [comment]
字符串是不可改变类型。
