### ISSUE TITLE
print输出的提问

### ISSUE THREAD

**Issue by myb007** [cfsmile/ooppy#12]
print(j,'*',i,'=',i*j,end=' ')
print("%d*%d=%2d" % (j, i, i * j), end=" ")
print("{}*{}= {:-2}".format(j,i,j*i),end=" ")
在输出的时候三者结果是一样的但是间距不一样是为什么

**Comment by passengeryjy** [comment]
这位同学，你这段代码可读性不是太好，你能否提供一下输出错误显示

**Comment by passengeryjy** [comment]
你的i.j如何定义的呢，

**Comment by passengeryjy** [comment]
You'll need to post more information in order for anyone to understand the problem. This might include example code, a longer description, perhaps even screenshots of the issue,
