### ISSUE TITLE
Recursion

### ISSUE THREAD

**Issue by lslflying** [cfsmile/ooppy#17]
def get_TR(mat):
    mat_c = mat**2
    if mat_c == mat:
        return mat
    else:
        return get_TR(mat_c)
mat的8次方等于mat的4次方
get_TR(mat2) return get_TR(mat4)
get_TR(mat4) return mat4
当递归结束时应返回mat4，
但最终的返回结果是mat4和一个None
请问是为什么呢

**Comment by lslflying** [comment]
已解决

**Comment by qtg666** [comment]
怎么还跑这来问了
