### ISSUE TITLE
A mistake in Part1.ipynb - dict.popitem()

### ISSUE THREAD

**Issue by cavedweller509** [cfsmile/ooppy#18]
Dear cfsmile,
There is a mistake in *Part1.ipynb* when you explain the method **dict.popitem()** . You say that the method will return a random pair. But when I tested in my Python I found that it will return me the last element pair inserted into the dict. Then I visited [here](https://docs.python.org/3/library/stdtypes.html?highlight=popitem#dict.popitem) and found that "Pairs are returned in LIFO order from python3.7". So I think it should be modify in the new tutorials.
Your stu, An Hongjun.

**Comment by cfsmile** [comment]
Dear An,

You are right. "Changed in version 3.7: LIFO order is now guaranteed." The mistake is absolutely on my side.
I will make the corrections.

Thanks for pointing it out.

Best regards
