### ISSUE TITLE
return语句的作用

### ISSUE THREAD

**Issue by wangxiaoxiaoi** [cfsmile/ooppy#5]
def test():
    print('This is printed')
    return
    print('This is not')

x = test()
print(x)  # None  
为什么x输出的是空，而'This is not'不能输出?
因为return代表这函数定义的结束，后面的语句不予理会。
变式：
在利用递归求阶乘是有如下代码：

def frac(n):
    if n == 1:
        return 1
    else:
        return n * frac(n-1)
    print('n in this level is %d' % n) 
return后面的print不予理会
若frac(5)，则直接输出120。
因此我不太理解在return后面写这一句的含义。

**Comment by cfsmile** [comment]
> 提问时，将文字排版，可以提高可读性，方便大家理解你的问题，并帮助做答。
   我试着排了下版，尤其是代码部分。供你参考。写issue时，上面有个<>符号，名"Insert Code"，可以帮助排版代码。
   多个问题分开写，每条issue一个问题，方便讨论解答。
   另外，努力使行文简洁。

```
def test():
    print('This is printed')
    return
    print('This is not')

    x = test()
    print(x)  # None  
```
Q: 为什么x输出的是空，而'This is not'不能输出?
A: 因为return代表这函数定义的结束，后面的语句不予理会。
变式：
在利用递归求阶乘是有如下代码：
```
def frac(n):
    if n == 1:
        return 1
    else:
        return n * frac(n-1)
    print('n in this level is %d' % n) 
```
return后面的print不予理会
若frac(5)，则直接输出120。
Q: 因此我不太理解在return后面写这一句的含义。

**Comment by qtg666** [comment]
这里是递归调用frac，输出的是n的阶乘。关于第二个问题，我觉得一方面这里print的缩进有问题，应该与return对齐；再者print应写在return语句上面，否则在return处函数结束，print没有作用（这里print的作用是输出该阶上n的值）。我认为代码可以改为：
```
def frac(n):
    if n == 1:
        return 1
    else:
        print('n in this level is %d' % n) 
        return n * frac(n-1)
```

**Comment by Gao827931838** [comment]
第二个问题是缩进有问题吧，print里面的东西好像也有问题，原代码中print中的n应该是想输出函数里的n。我感觉代码可以这样写
```
x=int(input())
def frac(n):
    if n == 1:
        return 1
    else:
        return n * frac(n-1)
print('%d in this level is %d' % (x,frac(x))

**Comment by qtg666** [comment]
楼上代码有点问题吧。。一方面最后的print少了一半括号，导致程序错误；另一方面楼上对‘in this level’的理解有误，它的意思是打印某一阶的数，而不是打印阶乘的最终结果，所以如果非要这么编代码的话也要改这一串英文，不然打印出的就是一句不知所云的话。最重要的是这一串代码不能被直接调用，为什么不把开头结尾两句放进frac函数里呢？这样只需要调用这个函数就能实现相应功能了。
