### ISSUE TITLE
同一程序执行两种不同最低输出限的logging模块

### ISSUE THREAD

**Issue by sharary** [cfsmile/ooppy#6]
在同一程序中，希望在日志文件和控制台中输出不同的log，比如在日志文件中输出bedug及其以上级别的log，在控制台中输出info及其以上级别的log。下面想出了一个比较麻烦的解决方法：
```
import logging as log1
import logging as log2


log1.basicConfig(filename = 'mudball-log.log',
                            format = '%(level)s  %(asctime)s : %(message)s',
                            level = log1.debug)

log2.basicConfig(format = '%(level)s %(asctime)s : %(message)s',
                            level = log2.info)


log1.bebug(...)     # will be printed
log2.info(...)      # will be printed
log2.debug(...)     # will not be printed
```
这个方法要将每个log传入log1和log2，而且在调试中返现这些代码是**不能运行**的：
> TypeError: Level not an integer or a valid string: <function debug at 0x0000014FCB5101E0>

所以想知道应该如何解决开头所叙述的问题。

**Comment by zxjzel** [comment]
logging 导入一次就可以了  不用多次导入   他那个有handler  可以通过设置streamhandler  和  filehandler实现
